apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: springbootapp
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.large
    desiredCapacity: 2
    ssh: # use existing EC2 key
      publicKeyName: ak-instance-usw2
